### ISSUE TITLE
Date field in the plaso.l2tcsv.conf is populated with csv load time

### ISSUE THREAD

**Issue by mark-hallman** [cvandeplas/ELK-forensics#5]
Hello,

I am having some trouble loading Plaso CSV data into ELK using the plaso.l2tcsv.conf.  The issue is that the @timestamp field is being populated with the CSV load time and not the time created by the mutate statements in the conf file that concatenates the date, time, and timezone.  

I am using the unmodified plaso.l2tcsv.conf file from this GitHub page.  

LogStash version: 5.6.1
Elasticsearch version: 5.6.0
Kibana Version:  5.6.0
OS: Ubuntu 16.04

I have included the Logstash log file and a screenshot of the loaded data in Kibana.  

Thoughts on what might be causing the issue?

Thanks

-Mark 

mark.hallman@gmail.com
Skype: mhallman

![lt2_load_kibana](https://user-images.githubusercontent.com/16808320/32501400-82808a0a-c39d-11e7-9242-5e2db5d25650.jpg)

[logstash-plain.log](https://github.com/cvandeplas/ELK-forensics/files/1450532/logstash-plain.log)

**Comment by cvandeplas** [comment]
can you give one example line of your CSV?

**Comment by mark-hallman** [comment]
Christophe,

Attached is the test file that I have been using.  10 line from a psort.py
filter.

I have also attached the conf file just in case I have an old version.

Thanks for taking a look at this.

-Mark

-Mark

mobile:830.255.1551
Skype: mhallman

**Comment by cvandeplas** [comment]
your attachment is not available in the issue on github. you can email it to me directly if you prefer. christophe at vandeplas dot com.

**Comment by cvandeplas** [comment]
The conclusion was: 
> > 
> I was able to get the conf file to work by making a small change to the match statement.  I used the "ZZZ" format for the timezone.
> 
```
    date {
      # match => ["l2t_date", "MM/dd/YYYY HH:mm:ss z" ] .       # This format does NOT work
      match => ["l2t_date", "MM/dd/YYYY HH:mm:ss ZZZ" ] .  # This format works
     }
```
> 
> Using the ZZZ format works for most situations.  I think I am going to need some kind of custom filter / function to get the timezone name converted to the correct joda-time name or offset. 
> 
> Some of timezone names that are possible from the psort.py output are in the list of valid joda-time names, like 'UTC" and "EST" but some are not.  One example is "CST" is "CST6CDT".  Who comes up with this stuff?  
> 
> http://joda-time.sourceforge.net/timezones.html
> 

I believe this is caused by the timezone-related parameters given when exporting the l2tcsv with plaso.
